spring:
  application:
    name: airline

  datasource:
    url: jdbc:mysql://localhost:3306/Airline?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: DbUser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

logging:
  level:
    "[com.seu.airline]": DEBUG
    "[org.springframework.jdbc]": DEBUG
    root: INFO
