spring:
  application:
    name: airline

  datasource:
    url: jdbc:mysql://localhost:3306/Airline?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: DbUser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080
